_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 76
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 76
                - 77
            "3":
                - 1
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.11
            "5": 0.18.5
            "8":
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
batch_size:
    value: 8
in_channels:
    value: 8
learning_rate:
    value: 0.001
method:
    value: random
metric:
    value:
        goal: maximize
        name: val_f1
num_epochs:
    value: 5
num_heads:
    value: 3
optimizer:
    value: adam
out_channels:
    value: 8
parameters:
    value:
        batch_size:
            values:
                - 8
        in_channels:
            value: 8
        learning_rate:
            value: 0.001
        num_epochs:
            value: 5
        num_heads:
            values:
                - 3
        optimizer:
            values:
                - adam
        out_channels:
            values:
                - 8
        random_state:
            value: 42
        test_size:
            value: 0.3
        weight_decay:
            values:
                - 0
random_state:
    value: 42
test_size:
    value: 0.3
weight_decay:
    value: 0
