_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 76
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 76
                - 77
            "3":
                - 2
                - 23
                - 55
            "4": 3.10.11
            "5": 0.18.5
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
learning_rate:
    value: 0.0001
num_epochs:
    value: 5
num_heads:
    value: 1
weight_decay:
    value: 0.001
