wandb_version: 1

batch_size:
  value: 32
in_channels:
  value: 8
learning_rate:
  value: 0.00011669847931404637
num_epochs:
  value: 5
num_heads:
  value: 1
optimizer:
  value: sgd
out_channels:
  value: 8
random_state:
  value: 42
test_size:
  value: 0.3
weight_decay:
  value: 0.001
