_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 76
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 76
                - 77
            "3":
                - 1
                - 2
                - 23
                - 55
            "4": 3.10.11
            "5": 0.18.5
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
batch_size:
    value: 32
in_channels:
    value: 6
learning_rate:
    value: 1e-05
num_epochs:
    value: 5
num_heads:
    value: 2
optimizer:
    value: adam
out_channels:
    value: 8
random_state:
    value: 42
test_size:
    value: 0.3
weight_decay:
    value: 0.0001
