wandb_version: 1

batch_size:
  value: 32
in_channels:
  value: 6
learning_rate:
  value: 0.1
num_epochs:
  value: 5
num_heads:
  value: 4
optimizer:
  value: sgd
out_channels:
  value: 4
random_state:
  value: 42
test_size:
  value: 0.3
weight_decay:
  value: 1.0e-05
