wandb_version: 1

batch_size:
  value: 4
in_channels:
  value: 8
learning_rate:
  value: 0.00402516532891167
num_epochs:
  value: 5
num_heads:
  value: 3
optimizer:
  value: sgd
out_channels:
  value: 4
random_state:
  value: 42
test_size:
  value: 0.3
weight_decay:
  value: 0.001
