wandb_version: 1

batch_size:
  value: 16
in_channels:
  value: 8
learning_rate:
  value: 4.523550814265946e-05
num_epochs:
  value: 5
num_heads:
  value: 3
optimizer:
  value: adam
out_channels:
  value: 12
random_state:
  value: 42
test_size:
  value: 0.3
weight_decay:
  value: 0.001
