wandb_version: 1

batch_size:
  value: 32
in_channels:
  value: 8
learning_rate:
  value: 0.001005297923237924
num_epochs:
  value: 5
num_heads:
  value: 5
optimizer:
  value: sgd
out_channels:
  value: 12
random_state:
  value: 42
test_size:
  value: 0.3
weight_decay:
  value: 0.001
