wandb_version: 1

batch_size:
  value: 8
learning_rate:
  value: 0.01
num_epochs:
  value: 10
num_heads:
  value: 3
optimizer:
  value: adam
out_channels:
  value: 4
random_state:
  value: 42
test_size:
  value: 0.3
weight_decay:
  value: 1.0e-05
