_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 76
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 76
                - 77
            "3":
                - 1
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.11
            "5": 0.18.5
            "8":
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
batch_size:
    value: 8
in_channels:
    value: 8
learning_rate:
    value: 0.0013987609232725415
method:
    value: random
metric:
    value:
        goal: maximize
        name: val_f1
num_epochs:
    value: 5
num_heads:
    value: 4
optimizer:
    value: sgd
out_channels:
    value: 4
parameters:
    value:
        batch_size:
            values:
                - 8
                - 16
                - 32
        in_channels:
            value: 8
        learning_rate:
            distribution: log_uniform_values
            max: 0.01
            min: 1e-05
        num_epochs:
            value: 5
        num_heads:
            values:
                - 1
                - 2
                - 3
                - 4
                - 5
        optimizer:
            values:
                - adam
                - sgd
        out_channels:
            values:
                - 4
                - 8
                - 12
                - 16
        random_state:
            value: 42
        test_size:
            value: 0.3
        weight_decay:
            values:
                - 0
                - 1e-06
                - 1e-05
                - 0.0001
                - 0.001
random_state:
    value: 42
test_size:
    value: 0.3
weight_decay:
    value: 1e-06
